### ISSUE TITLE
Gnome 41 compatibility

### ISSUE THREAD

**Issue by apinter** [zagortenay333/timepp#177]
Hi there,

Will `Time++` be available for Gnome 41? Not rushing, pushing or nagging, just genuinely curious.

**Comment by tanayparashar** [comment]
I am also curious when will support for GNOME 41 come?

**Comment by lev741** [comment]
It looks like it is working well with Gnome 41 (Fedora 35).
Just change metadata.json:
  "shell-version": [
    "40",
    "41"
  ],

**Comment by tanayparashar** [comment]
Thanks,
it is working.

**Comment by zagortenay333** [comment]
OK, I bumped the version.
