### ISSUE TITLE
Todo: created date isn't appended just after creation

### ISSUE THREAD

**Issue by przepompownia** [zagortenay333/timepp#178]
Please look at the fresh todo entry. There is no created date. 
![image](https://user-images.githubusercontent.com/11404453/137319285-da917004-79b7-4080-814e-af59b9660e14.png)
After inserting any character `created` date is appended as it were expected for me at the creation:
![image](https://user-images.githubusercontent.com/11404453/137319405-356da33d-2bb8-4d00-b781-577993832925.png)
gnome-shell 40.5-1+b1 on Debian sid.

(edit) I don't forget that this parameter is optional but it such appending looks like not intentional behavior.

**Comment by zagortenay333** [comment]
Does the date appear in the text file but not in the extension when you add a new task? If so, it's a rendering issue that I honestly can't fix. It's some strange quirk of gnome shell UI.

**Comment by przepompownia** [comment]
Since some weeks I have gnome-shell upgraded to version 41, on which this extension does not work. Let's come back to the topic after making it working there.

**Comment by zagortenay333** [comment]
It works now on 41.

**Comment by przepompownia** [comment]
Indeed, the creation date appears in text file but is not visible in a timepp block. BTW, thanks for making compatibility with v41.

**Comment by zagortenay333** [comment]
Yeah I don't know how to fix that. I remember doing some weird hacks to work around this, but it never worked.

**Comment by przepompownia** [comment]
Thanks for at least your interest :+1:

**Comment by zagortenay333** [comment]
The new version of the extension shouldn't have this problem anymore.

**Comment by przepompownia** [comment]
For some months I still cannot get the current version from https://extensions.gnome.org/extension/1238/time/ for GNOME Shell 43 (v 44 is already present in Debian rc-buggy). 

I'll try to extract the released zip file, but I'm confused if the content should be extracted into `timepp@zagortenay333/` or the new name (cronomix) if it matters at all.

**Comment by zagortenay333** [comment]
The gnome site will take a while to update.

You extract the  zip and the folder will be already named correctly (cronomix@zagortenay333).

**Comment by przepompownia** [comment]
It started to work after manual unpacking. 

Thanks for the whole work. The sad news is that this tool has abandoned the todo.txt standard. It means incompatibility with other editors that respect it (for me, especially possible Neovim extensions). Compatibility was a strong point of timepp, independently of issues.

**Comment by zagortenay333** [comment]
When I'm in the mood I'll add an export feature. You could export the tasks to todo.txt. However, importing is not on the table. I just don't want to deal with the BS that comes with that.
