### ISSUE TITLE
Cannot close fullscreen

### ISSUE THREAD

**Issue by PeterlitsZo** [zagortenay333/timepp#179]
When Time++ open the full screen, I cannot close by its close icon 'x'.

![image](https://user-images.githubusercontent.com/25707198/140329020-b4b89c99-6b39-4954-8af8-64b3a6ee2e68.png)

(Left one)

I work on Ubuntu 20.04 LTS. What more information do I should give please?

**Comment by PeterlitsZo** [comment]
Well, sometime it works good, One more issue: if it show on the 2nd screen, I cannot scroll the content on 1st screen.

**Comment by x0thrmc-exe** [comment]
This same thing just happened to me also. I only have one screen so it covered the whole screen when the break notification popped up and prevented me from clicking on any other windows. There was no way to quit it or close the fullscreen window. Although I was able to interact with other windows via the keyboard. I left the computer and it went away automatically when the screen locked after inactivity.

**Comment by PeterlitsZo** [comment]
> This same thing just happened to me also. I only have one screen so it covered the whole screen when the break notification popped up and prevented me from clicking on any other windows. There was no way to quit it or close the fullscreen window. Although I was able to interact with other windows via the keyboard. I left the computer and it went away automatically when the screen locked after inactivity.

Yes. I try to read source code. But I cannot point out why it be wrong.

**Comment by zagortenay333** [comment]
Sorry can't help you folks. This bug is not purely in this extensions source code (at least I don't think so) but rather one of those bugs that occur when interacting with gnome shell. I don't want to deal with this bullshit right now.

**Comment by PeterlitsZo** [comment]
Oh thanks for your comments. I get it.

**Comment by zagortenay333** [comment]
The new version of the extension doesn't have these fullscreen things so closing.

**Comment by PeterlitsZo** [comment]
Thanks for your great job!
