### ISSUE TITLE
[suggestion] Hide hours in Pomodoro timer

### ISSUE THREAD

**Issue by rootsh0pf** [zagortenay333/timepp#181]
It would be nice if we could hide the hours in the pomodoro timer, since it usually does not run longer than one hour. Maybe with a switch in the settings right under "show seconds".

**Comment by zagortenay333** [comment]
Didn't I write not to make feature requests in the README?

**Comment by rootsh0pf** [comment]
Whoops, you are perfectly right, sorry for that! Note to self: Always read README first. ;)

**Comment by zagortenay333** [comment]
No problem. :)
