### ISSUE TITLE
When opening the configuration of the extension it jumps error

### ISSUE THREAD

**Issue by AngelBrielez** [zagortenay333/timepp#182]
OS: Ubuntu 20.04.3 LTS

The settings of extension timepp@zagortenay333 had an error:
```
Gtk.BuilderError: /home/angelo/.local/share/gnome-shell/extensions/timepp@zagortenay333/data/prefs.ui:21:1 Invalid object type 'GtkStackPage'
```

Stack trace:
```
Settings@/home/angelo/.local/share/gnome-shell/extensions/timepp@zagortenay333/prefs.js:22:22
buildPrefsWidget@/home/angelo/.local/share/gnome-shell/extensions/timepp@zagortenay333/prefs.js:578:20
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by zagortenay333** [comment]
Are you using the right version of the extension for your version of gnome shell?

**Comment by AngelBrielez** [comment]
https://i.imgur.com/CWu1TKD.jpg

**Comment by AngelBrielez** [comment]
Yes, the extension was working normally, with its configuration window and its utility, but now the extension is still doing its job, but the configuration window gives me the following error.

https://i.imgur.com/CWu1TKD.jpg

**Comment by zagortenay333** [comment]
What version of the extension an gnome shell are you using?

**Comment by AngelBrielez** [comment]
Shell version is: 3.36.9, Time ++ extension version: 160

**Comment by zagortenay333** [comment]
Hmm, it looks like I didn't remove support for 3.36 when I updated to 40. I think you have to use an older version of the extension for 3.36: https://github.com/zagortenay333/timepp/tags

**Comment by AngelBrielez** [comment]
Gracias por tu ayuda y tu tiempo, descargué la versión que me enviaste y funciona perfectamente, pero también noté que la extensión Time ++ en extensions.gnome.org/, ya no se instala correctamente ni automáticamente, arroja error al instalarla, espero que sea algo temporal 😅

**Comment by AngelBrielez** [comment]
Thanks for your help and your time, I downloaded the version you sent me and it works perfectly, but I also noticed that the Time ++ extension in extensions.gnome.org/, no longer installs correctly or automatically, it throws error when installing it, I hope it is something temporary 😅
