### ISSUE TITLE
My Requests

### ISSUE THREAD

**Issue by mt190502** [zagortenay333/timepp#183]
Hello, this plugin is very nice. it works great for me. But I would have a few requests. Thanks
1) Choosing different fonts for full-screen features such as stopwatch, pomodoro
2) Change font size
![image](https://user-images.githubusercontent.com/62564400/145378446-bff900bf-b5f0-4e87-8958-a5ad70ee826c.png)

**Comment by zagortenay333** [comment]
I don't take feature requests anymore.
