### ISSUE TITLE
Freezes completely Gnome 41.2

### ISSUE THREAD

**Issue by digitalillusion** [zagortenay333/timepp#184]
I am using only time tracker, nothing particular in the configuration
![immagine](https://user-images.githubusercontent.com/94325/146141780-3f4ad89f-5124-4e42-9fff-622f9e827916.png)
![immagine](https://user-images.githubusercontent.com/94325/146141868-95bdf6a3-bff2-49a9-beff-92d588e5a226.png)
It creates a daily file and an yearly file:
2021__time_tracker.csv
TODAY__time_tracker.csv

At the end of day, or upon first access after midnight, it attempts to transfer the content of TODAY__time_tracker.csv into 2021__time_tracker.csv

The problem is that the lines inside TODAY__time_tracker.csv are not removed, so it keeps adding duplicates of them into 2021__time_tracker.csv until, after a few seconds, there are several dozens of duplicates and system hangs.

The workaround is to manually copy the content of TODAY__time_tracker.csv into 2021__time_tracker.csv before midnight.

I have gone through the code and it seems to be correct. I suspect that there is some kind of file lock issue that prevents the contents of TODAY__time_tracker.csv to be removed

**Comment by zagortenay333** [comment]
Either there is something wrong with the file API in gnome shell, or I'm misunderstanding how it's supposed to be used. Say you have a file monitor on some file. You turn it off, write to the file with a blocking operation, turn the file monitor on, and it fires immediately to signal the previous write...

I don't have the patience to deal with this kind of BS anymore. If there is someone more familiar with gnome shell, feel free to help out.

**Comment by guiNovais** [comment]
I am having the same issue with the extension. First I though it was due to the configuration, aldough even by reseting all the custom values os this extension (via dconf editor), it still freezes with a few seconds after login.

These are my system settings:
```
 ██████████████████  ████████     guilherme@asus
 ██████████████████  ████████     OS: Manjaro 21.2.0 Qonos
 ██████████████████  ████████     Kernel: x86_64 Linux 5.15.7-1-MANJARO
 ██████████████████  ████████     Uptime: 14m
 ████████            ████████     Packages: 1216
 ████████  ████████  ████████     Shell: zsh 5.8
 ████████  ████████  ████████     Resolution: 3286x1080
 ████████  ████████  ████████     DE: GNOME 41.2
 ████████  ████████  ████████     WM: Mutter
 ████████  ████████  ████████     WM Theme: Adwaita-maia-compact-dark
 ████████  ████████  ████████     GTK Theme: Adwaita-maia-compact-dark [GTK2/3]
 ████████  ████████  ████████     Icon Theme: Papirus-Dark-Maia
 ████████  ████████  ████████     Font: Noto Sans 11
 ████████  ████████  ████████     Disk: 51G / 224G (24%)
                                  CPU: Intel Core i7-4500U @ 4x 3GHz [51.0°C]
                                  RAM: 3141MiB / 11854MiB
```

BTW, X11 and Wayland have the same behavior.

**Comment by digitalillusion** [comment]
The issue is with file_replace_contents failing assertion on content != null when passing an empty string. The solution is to pass a newline instead. Opening PR to fix this
