### ISSUE TITLE
Hide the number of hours when zero

### ISSUE THREAD

**Issue by pellk** [zagortenay333/timepp#186]
https://github.com/zagortenay333/timepp/blob/de43fa28591382235657c03fd0258d240c5a9047/sections/pomodoro.js#L462-L475
Hello there and thank you for this awesome extension. I use the pomodoro section regularly. My only request is to hide the number of hours (at least via settings) when it's double 0s, which is almost always the case.

**Comment by zagortenay333** [comment]
I don't take feature requests anymore.
