### ISSUE TITLE
Config should not be in the .cache dir of user's home

### ISSUE THREAD

**Issue by llabusch93** [zagortenay333/timepp#188]
Hello,
to put configuration files in the cache dir (<USER_HOME>/.cache) is not a good practice and actually wrong. The config should go into the <USER_HOME>/.config.
I set for instance the cache dir to a TMPFS (so in RAM), resulting the configuration of timepp get lost after each reboot. That's pretty annoying...

Cheers,

**Comment by zagortenay333** [comment]
Fixed.
