### ISSUE TITLE
Please upgrade to gnome 42

### ISSUE THREAD

**Issue by martinandersen3d** [zagortenay333/timepp#190]
Thank you for your work on this extension.

Please consider updating it to support Gnome 42

**Comment by rduivenvoorde** [comment]
fyi I've locally updated the version number in 

`/.local/share/gnome-shell/extensions/timepp@zagortenay333/metadata.json`

to 42, so the shell-version part becomes:

```
  "shell-version": [
    "40",
    "41",
    "42"
  ],
```

And for what I use it, most things work...

One thing (I will create an issue for), is that I had a blocking screen, which I could not escape from, when I put the time (by accident) on big screen...

If others maybe can report back here if they have (other) issues, I'm happy to do an actual tiny PR (but I'm not not sure enough there are other issues in 42)

**Comment by rduivenvoorde** [comment]
Ah, sorry, the full screen issue was already reported and seems not easy to fix: 
https://github.com/zagortenay333/timepp/issues/179

**Comment by diogobaeder** [comment]
@zagortenay333 is there any chance we can get a working version for Gnome 42, even if the full screen support is disabled under that version? I don't know about the other users, but for me this extension is really important and it's been a struggle for me to not have it available under Gnome 42...

**Comment by zagortenay333** [comment]
@diogobaeder With due respect, you shouldn't make this extension important to you. This project is in extremely low maintenance mode and if it wasn't for volunteers it would be deprecated a long time ago. This extension should be used casually when/if it's available on a given version of gnome shell. Don't put all your eggs in this basket.

**Comment by diogobaeder** [comment]
@zagortenay333 fair enough, I won't count on it then. Thanks for the heads up! 🙂

**Comment by landegt** [comment]
@diogobaeder I've just opened a pull request with the changes you described (https://github.com/zagortenay333/timepp/pull/192).
Please let me know if you find any issues.

**Comment by digitalillusion** [comment]
I've opened #195 to fix known problems with gnome shell 42. Differently from #192, fullscreen capability is maintained (since it's useful at least in timetracker)
