### ISSUE TITLE
Settings don't work on Pop_OS 22.04

### ISSUE THREAD

**Issue by thiagobarbosa-dev** [zagortenay333/timepp#193]
When opening the settings, the error appears:

The settings of extension timepp@zagortenay333 had an error:
```
Error: set_titlebar() is not supported for Adw.Window
```

Stack trace:
```
set_titlebar/<@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:51:17
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by zagortenay333** [comment]
Are you using a gnome shell version that is supported?

**Comment by landegt** [comment]
Pop_OS 22.04 is using gnome 42, this issue is fixed in a pull request I opened a little while ago #192.

**Comment by hrishiksh** [comment]
Hi, @landegt,  can you direct me how to compile and install this plugin from your updated repo. As your PR is not merged yet. I am using gnonme 42 with popos 22.04

**Comment by landegt** [comment]
Absolutely @hrishiksh,
 
It is easiest to just clone my repo directly 
`git clone https://github.com/landegt/timepp.git`
You will now have to rename the folder and move it to the correct location
`mv timepp ~/.local/share/gnome-shell/extensions/timepp@zagortenay333`
All that is left now is to press `Alt F2` then type `r` and press `Enter`, or log out and back in.
You can now enable the extension in the gnome extensions app 

If you have any questions please reach out to me.
