### ISSUE TITLE
Task can't be added by pressing Enter or Shift+Enter or Ctrl+Enter

### ISSUE THREAD

**Issue by blackdaemon** [zagortenay333/timepp#199]
Using Enter key just adds new line to the task text. It would be nice if any combination of Ctrl/Shoft + Enter would add the task without need to click the OK button.
- Enter to add new row
- Ctrl+Enter to confirm/add the task

**Comment by zagortenay333** [comment]
Not really needed. Maybe some later time I might add some more sophisticated keyboard handling.
