### ISSUE TITLE
Adding the task to Kanban board should add the +

### ISSUE THREAD

**Issue by blackdaemon** [zagortenay333/timepp#200]
I have a kanban board with 3 lists: todo, in_progress, done.
It would be nice if when adding the task by clicking on "Add new task" on any list would add the +list automatically to the task text.
For instance, adding the task to "todo" list would open the task window with following text:

| +todo

(Where | represents the cursor)

**Comment by zagortenay333** [comment]
This doesn't really apply to the new version of the extension so closing.
