### ISSUE TITLE
Only 1 option there in settings

### ISSUE THREAD

**Issue by Avijneyam** [zagortenay333/timepp#202]
![image](https://user-images.githubusercontent.com/72083951/182431896-ed093252-23c3-4ae8-9d17-de8572ec1e88.png)
was 4-5 tabs in settings but now showing only one

**Comment by sgrzy01** [comment]
same issue here... 22.04.1 / 42.2

**Comment by landegt** [comment]
The issue is fixed in #203, would be great if you could check it out and comment that it works. That way it can get merged more quickly.

**Comment by sgrzy01** [comment]
What timing! I literally hit submit and the fixed appeared... applied and it is indeed fixed!  Thank you!

**Comment by landegt** [comment]
@sgrzy01 Glad to help, could you comment on the PR itself too, please? Just to document that it works on multiple systems and has been tested. Thanks

**Comment by Avijneyam** [comment]
Thank You @landegt <3
