### ISSUE TITLE
Cannot interact with popup menu buttons using keyboard

### ISSUE THREAD

**Issue by igor-103** [zagortenay333/timepp#204]
It is impossible to trigger selected button in popup menu using keyboard keys Space or Enter.
Steps to reproduce:

1. Trigger popup menu to appear either by shortcut or by clicking on it.
2. Press Tab or Shift+Tab in order to focus some button, e.g "Start" of the Stopwatch.
3. Press Space or Enter.

_Expected result._ Stopwatch starts.
_Actual result._ Nothing happens.

**Comment by zagortenay333** [comment]
Should be fixed now.

**Comment by igor-103** [comment]
Still doesn't work on my computer unfortunately

**Comment by zagortenay333** [comment]
Are you using the new version of the extension?

**Comment by igor-103** [comment]
I'm not sure where to check it. In the Extensions application I see some number 165 near Time++. Is this it?

**Comment by zagortenay333** [comment]
Nope. The extension is renamed to cronomix and completely rewritten. Go to the readme file for instructions on how to install it

**Comment by igor-103** [comment]
Have installed. Thanks a lot!

**Comment by zagortenay333** [comment]
Cheers!
