### ISSUE TITLE
Editing todos hangs gnome-shell on gnome 42 / fedora 36

### ISSUE THREAD

**Issue by Yannik** [zagortenay333/timepp#207]
Hi,

unfortunately, editing a todo results in a complete hangup of the gnome shell after upgrading to gnome 42 / fedora 36. 

This was working fine on gnome 41/fedora 35.

**Comment by psydvl** [comment]
Duplicate https://github.com/zagortenay333/timepp/issues/201

**Comment by Yannik** [comment]
Thanks, you are right @psydvl
