### ISSUE TITLE
Gnome 43 support incoming?

### ISSUE THREAD

**Issue by OperationNorthwoods** [zagortenay333/timepp#209]
Just curious. Discovered this extension today, and heard about the recent GNOME 43 release. I'm expecting the update on Arch Linux in  a couple weeks at most.

**Comment by zagortenay333** [comment]
Yes it will eventually come. I'm currently working on a somewhat big update, so it'll take a while.

**Comment by rcsm17** [comment]
What about the issue when the user click on the pencil icon to modify an item that stuck the entire desktop  ? Are you plan to solve this issue with the next release or you can't ?

**Comment by zagortenay333** [comment]
@rcsm of course

**Comment by digitalillusion** [comment]
Meanwhile, you can use my forked version with gnome 43. 

https://github.com/digitalillusion/timepp/releases/tag/166

**This is not an official release**. I can open a merge request to this repository if needed

**Comment by Yannik** [comment]
@zagortenay333 Are you still working on this? :)

**Comment by zagortenay333** [comment]
Yes, should be done in about a week or 2. In time for the fedora release.

Here is a preview (I ditched the todo.txt format and ship a custom markup lang):

![Screenshot from 2023-04-14 14-06-35](https://user-images.githubusercontent.com/11144630/232769282-00c893ae-4251-4088-b148-5a75c1810bee.png)

**Comment by Yannik** [comment]
> Yes, should be done in about a week or 2. In time for the fedora release.

That's great!
 
> Here is a preview (I ditched the todo.txt format and ship a custom markup lang):

Hm, I personally liked the line-based todo.txt very much, because I could filter the tasks with grep etc.

Do you think it'll be possible to still do that with the new format (with only single line tasks)?

**Comment by zagortenay333** [comment]
If you write the task on one line it will be on one line. So your todos can look like this:

```
[x] lorem ipsum.
[ ] lorem ipsum.
[#1] lorem ipsum.
[@foo] lorem ipsum.
```

But you can't do that thing where the extension squashes a multi-line task to one line by inserting `\n`.

**Comment by Yannik** [comment]
Would you mind posting a sample of the new todo.txt format?

Currently, it looks like this for me:
```
2023-04-16 <my-todo-text>
```

**Comment by zagortenay333** [comment]
I already did above. In general, this markup language is not as easy to parse as `todo.txt`. Things aren't in rigid positions so it will probably be harder to grep stuff.

**Comment by Yannik** [comment]
I see. Thanks for your efforts!

**Comment by zagortenay333** [comment]
Done.
