### ISSUE TITLE
Adding a task crashes GNOME Shell

### ISSUE THREAD

**Issue by frederik-elwert** [zagortenay333/timepp#212]
On Ubuntu 22.04 (GNOME 42.4), when adding a task, GNOME Shell crashes. On X, the Shell is restarted, but on Wayland, the whole session is terminated.

Steps to reproduce:

1. Click on the panel icon and select "New Task".
2. Fill in the task description and hit `Enter`.

What happens:

The updated dropdown menu with the new task is shown, but then everything including the mouse cursor freezes and after a few seconds the shell crashes/restarts.

I tried this on two different machines with Ubuntu 22.04, and it happens on both of them.

**Comment by zagortenay333** [comment]
I'm working on a big update to the extension which will fix this among other things. It will take some time though..

**Comment by ericduvic** [comment]
This is still broken with the version released to the Gnome extension store. Has the new version been released? Is there any more debug info that I can provide?
