### ISSUE TITLE
Cant focus on alarm edit button.

### ISSUE THREAD

**Issue by mursalatul** [zagortenay333/timepp#217]
When I am trying to edit my alarm, in spit of hovering the edit button, I cant focus the it. Sometimes it is not showing and when it is showing it is does not taking the focus. But when I am trying this after setting 2 alarms, i can edit the 2nd one. First one is still unfocused. 
![image](https://user-images.githubusercontent.com/79168756/220094101-7659ffc1-6805-4b13-b369-916164a8066f.png)

**Comment by ezekiel-alexrod** [comment]
Same here on Pop!_OS 22.04 GNOME 42.5

**Comment by 3z3kI31** [comment]
Same here on Pop!_OS 22.04 GNOME 42.5

**Comment by zagortenay333** [comment]
Should be fixed now.
