### ISSUE TITLE
Slide bar in timer not appears in Fedora 36 and latest ubuntu

### ISSUE THREAD

**Issue by M4rQu1Nh0S** [zagortenay333/timepp#219]
The timer slide bar not appear in some distros like fedora 36, latest ubuntu versions and others with gnome 43. In fedora 36 the gnome is the version 42.5.

Only in Ubuntu 22.04 the slide bar appears without issues:
![Captura de tela de 2023-03-02 17-00-40](https://user-images.githubusercontent.com/3124203/222539115-367da997-a673-4a31-a31b-35d265b4e413.png)

**Comment by M4rQu1Nh0S** [comment]
Changing the theme for the gnome shell makes the sidebar appear again, so the issue is with the default gnome-shell 43 theme.
An update is needed to fix this issue, a workaround is using a different theme for gnome-shell with gnome-tweaks.

**Comment by zagortenay333** [comment]
The new version of this extension won't use a slider so that will fix it.

**Comment by zagortenay333** [comment]
No slider, no problem. This is fixed in the latest version.
