### ISSUE TITLE
Timer presets

### ISSUE THREAD

**Issue by lev741** [zagortenay333/timepp#221]
After load preset and triger start timer, old one is counting down. 
Button Reset helps.

Reproduce: 
1. Set 2 different preset
2. Choose first.
3. start
4. stop
5. Choose second
6. start

After step 6. the first preset is counting down

**Comment by zagortenay333** [comment]
I don't think it would be right for a currently unfinished timer to be reset when you switch the preset. You should either let that timer run to completion or reset it manually.

**Comment by lev741** [comment]
I agree. When is running.
But the timer is not running anymore. After I switch to other preset I see new number of preset. When I click start the old one is counting down.

**Comment by zagortenay333** [comment]
I don't get what you're saying.

If you pause a timer at say 4 seconds then switch to preset of 16 seconds, the timer will be paused and still show 4 seconds. You press play, the 4 seconds run out, and next time you press start it begins at 16 seconds.

Does that not happen?

[Screencast from 2023-06-05 14-59-51.webm](https://github.com/zagortenay333/cronomix/assets/11144630/cbf5786a-e277-4bdd-b0bc-b86f1327d255)

**Comment by lev741** [comment]
Hmm, I see... 
My scenario is to brew tea. I brew black, green, herbal. It means 5,3,10 minutes. 
When I want to brew black tea. I need to choose 5 minutes. I choose it, I see 5 minutes, but only after start I see that there is selected something previously chosen (10 minutes) and that is not I want. I want 5 mitutes that I chose, not random. 

So I mean, when I make selection, previously state should be omitted and new one should be there. Like reset.

[Záznam obrazovky z 2023-06-06 11-03-56.webm](https://github.com/zagortenay333/cronomix/assets/72345076/70e3967a-0210-477b-8134-94e951a2a97e)

**Comment by zagortenay333** [comment]
Ohh, wait a minute. That's just a bug.

I thought you said that when the timer is *paused* and you switch the preset. But here the timer is *reset* and switching the preset doesn't actually switch the timer.

I just pushed a fix.
