### ISSUE TITLE
Todo file from timepp not recognized?

### ISSUE THREAD

**Issue by Yannik** [zagortenay333/timepp#222]
Trying to upgrade from timepp, I have:
1. disabled timepp extension
2. installed cronomix extension
3. selected my todo file from timepp in cronomix

Unfortunately, the task list remains empty. Is importing tasks from timepp not supported?

**Comment by zagortenay333** [comment]
The new version of the extension uses a completely different format. A custom markup language.
Todo.txt is no longer supported.

**Comment by Yannik** [comment]
@zagortenay333 Yes, I know :-)

However, importing tasks from the old format is not planned/supported?

**Comment by zagortenay333** [comment]
I won't be adding import features, sorry. Dealing with other people's time formats is just a lot of tedious BS to deal with. I did open an issue myself for adding an export feature though.
