### ISSUE TITLE
Help panes cut off at the bottom of the screen

### ISSUE THREAD

**Issue by Yannik** [zagortenay333/timepp#223]
The help panes are cut off at the bottom of the screen and it is not possible to scroll them.

Example:
![Screenshot from 2023-06-06 12-09-48](https://github.com/zagortenay333/cronomix/assets/801996/af91c16d-246e-420f-98ec-a1389a69e9c2)

This seems to be the case for all help panes which are long enough to extend to the bottom of the screen.

**Comment by zagortenay333** [comment]
Are you sure that they are cut off? You can scroll but the scrollbar is invisible until you hover over the popup.

**Comment by Yannik** [comment]
@zagortenay333 Yes, it is impossible to scroll. Also, no matter where I move the mouse, a scroll bar is not showing up.

**Comment by zagortenay333** [comment]
Ahh shoot. I can't reproduce this on my machine...

[Screencast from 2023-06-06 12-17-30.webm](https://github.com/zagortenay333/cronomix/assets/11144630/b8d5f569-fe01-4933-ab34-c8bd4852ab4f)

**Comment by zagortenay333** [comment]
Not sure how to tackle this...

**Comment by Yannik** [comment]
Here is a screen recording of the issue:
[Screencast from 2023-06-06 12-21-21.webm](https://github.com/zagortenay333/cronomix/assets/801996/62412dd2-a454-4d2d-8b94-e1100922688a)

Unfortunately you can't see my mouse, but I am moving it all over the pane and trying to scroll, but nothing happens.

**Comment by zagortenay333** [comment]
Could you try typing this in the gnome shell console (one line at a time):

    Main.layoutManager.findIndexForActor(global.stage)
    Main.layoutManager.getWorkAreaForMonitor(r(0)).height

You get the console by pressing `alt-f2` then `lg`.

Does it report roughly the height of your monitor?

**Comment by Yannik** [comment]
The first return value is 0, and the second one is 2096.

This is on a 3840x2160 screen with 200% scaling.

**Comment by zagortenay333** [comment]
Hmmm. Can you see if the problem happens when you are at 100% scaling?

**Comment by Yannik** [comment]
At 100% scaling the dpi is so high that the whole box fits on the screen.

**Comment by zagortenay333** [comment]
Can you change your resolution in the gnome settings to something smaller so that it doesn't fit. Modern software debugging right here! :D so sad...

**Comment by Yannik** [comment]
Yep, halving the resolution and setting scaling to 100% does indeed result in sucessful scrolling.
The output from `Main.layoutManager.getWorkAreaForMonitor(r(0)).height` is halved as well.

**Comment by zagortenay333** [comment]
What happens when you halve the resolution but set the scale to 200%?

**Comment by Yannik** [comment]
Everything is huge (and therefore, not alot of the panel fits on the screen), but scrolling works.

**Comment by zagortenay333** [comment]
So the issue is somehow related to scaling...

**Comment by lev741** [comment]
Same problem. I have 200% zoom. With lover resolution I not see scroll bar but mouse whell works. With zoom not working.

Btw: Do you plan to be this pages able to translate?

**Comment by zagortenay333** [comment]
Yeah I need to make the docs translatable as well. Forgot about that...

**Comment by zagortenay333** [comment]
Could you guys see if it works now? You'll have to download the extension from github.

**Comment by lev741** [comment]
I tested it, it works fine now.

**Comment by Yannik** [comment]
Works for me also. Thanks!
