### ISSUE TITLE
Task view flickering when hovering scroll bar with mouse pointer

### ISSUE THREAD

**Issue by Yannik** [zagortenay333/timepp#225]
The task view is flickering when hovering the scroll bar with the mouse pointer.

https://github.com/zagortenay333/cronomix/assets/801996/b505467d-b0a5-4d21-af5e-fa534dce60e8

**Comment by zagortenay333** [comment]
I can't play the video. It says file is corrupt.

**Comment by Yannik** [comment]
That's weird, it's playing for me, both in the browser, in gnome videos and in vlc. Could you try any of the latter?

**Comment by zagortenay333** [comment]
Sorry my bad, had some codec issues. The good news is I was able to replicate it. I'll fix it when I have time. The issue happens only when you hover over that scrollbar it seems.

**Comment by zagortenay333** [comment]
This should be fixed now.
