### ISSUE TITLE
Task creation date not saved

### ISSUE THREAD

**Issue by Yannik** [zagortenay333/timepp#226]
In timepp, the task creation date was automatically saved with the task. This was quite important to me.
Unfortunately, this does not seem to be the case with cronomix. 

Would it be possible to bring this feature back?

**Comment by zagortenay333** [comment]
Maybe later, when I'm in the mood.

**Comment by Yannik** [comment]
Thank you, that would be very nice :-)

**Comment by zagortenay333** [comment]
The extension now supports task creation date attributes.

Currently the way they are inserted automatically is that when you open the
task editor, the `created` attribute is added to the text buffer. However,
if you use the editor to make multiple tasks you'll have to copy/paste the
created date onto the additional tasks.

![Screenshot from 2023-06-07 13-08-46](https://github.com/zagortenay333/cronomix/assets/11144630/4698b922-0797-4987-a5ae-cdd24c3a05f1)

**Comment by Yannik** [comment]
Great, thank you!
