### ISSUE TITLE
Navigatability between panes

### ISSUE THREAD

**Issue by Yannik** [zagortenay333/timepp#227]
I think the new extension looks great.

However, I found it very annoying to navigate, because the buttons to exit the current pane are all in different places.

Here are a few examples (try to find the exit button within each!):

![Screenshot from 2023-06-06 12-43-07](https://github.com/zagortenay333/cronomix/assets/801996/a9ef4adb-0203-48bf-9127-a6bc8e0bf837)

![Screenshot from 2023-06-06 12-42-01](https://github.com/zagortenay333/cronomix/assets/801996/8ec7caac-ecce-4ac2-8d77-58110075facc)

![Screenshot from 2023-06-06 12-42-12](https://github.com/zagortenay333/cronomix/assets/801996/640b31b5-6c36-44ab-ac08-401228c50e34)

![Screenshot from 2023-06-06 12-47-09](https://github.com/zagortenay333/cronomix/assets/801996/4b13af7f-417a-4f29-8eff-b0be43de75cf)

![Screenshot from 2023-06-06 12-42-47](https://github.com/zagortenay333/cronomix/assets/801996/fc08579c-5da0-477e-aee2-8a29db68efac)

I think, beyond re-thinking the buttons, it would really help if pressing `ESC` would close the current pane, instead of closing the whole thing. 

For the task creation/deletion my suggestion would be to use `Enter` for saving the task, and `Shift`+`Enter` for entering a newline. Or the other way around. Just any way to save the task without having to move aroung with the mouse.

**Comment by zagortenay333** [comment]
Yeah looks quite uniform doesn't it? :D

Thing is, all the views are so different I couldn't think of a uniform back button that doesn't look weird... It will stay like this for now.

**Comment by zagortenay333** [comment]
There is at least some logic. Either the back button is a normal button with the text Ok or Cancel or similar or it's an x icon on an entry with a header.

**Comment by Yannik** [comment]
@zagortenay333 Would you be open to the ideas I had regarding keyboard navigation? Then it wouldn't matter so much anymore where the actual buttons are :-)

**Comment by zagortenay333** [comment]
Yeah some universal keyboard shortcut for `ok` and `close` that you can modify from the global settings makes sense. I'll add it when I'm in the mood.

Btw, you can toggle the markup help with the F1 key.

**Comment by Yannik** [comment]
Great, thanks!

**Comment by Yannik** [comment]
> Btw, you can toggle the markup help with the F1 key.

That's good to know, thank you.

**Comment by Yannik** [comment]
@zagortenay333 Has there been any changes to the ESC key behavior? Atleast in my tests ESC still closes all extension panes :-(

**Comment by zagortenay333** [comment]
I won't add this.
