### ISSUE TITLE
Visibility of timetracker running

### ISSUE THREAD

**Issue by Yannik** [zagortenay333/timepp#228]
Currently, it is not indicated on the gnome top bar icon whether the timetracker is running or not, so it is very easy to forget. A possible solution would be to display the yellow timetracker button instead of the check mark.

Additionally, it is not possible to see which task the timetracker is running on, in the task view. Simply displaying the yellow timetracker button on the task might help here.

I think that is all for now :-)

Thank you for your work on this great extension!

**Comment by zagortenay333** [comment]
You can always see which task the tracker is running on in the tracker view.

[Screencast from 2023-06-06 13-15-25.webm](https://github.com/zagortenay333/cronomix/assets/11144630/e7ad6838-ede2-4c4d-84f6-dc66f8e4e368)

And yeah, I little indication on the gnome panel makes sense.

Also, please avoid making feature requests. I even wrote this in the readme. This project is in a done state. I just want to fix bugs (if I can) and keep it low maintenance.

**Comment by zagortenay333** [comment]
This is done. When you run the time tracker it will show it on the panel.

**Comment by Yannik** [comment]
Looks great to me, thank you!
