### ISSUE TITLE
Translation not working

### ISSUE THREAD

**Issue by lev741** [zagortenay333/timepp#229]
Hi,
I'm not sure if I'm making a mistake but even I used fresh instalation of Fedora 38 and putting everything on right place (~/.local/share/gnome-shell/extensions/cronomix@zagortenay333/locale/cs/LC_MESSAGES/cronomix.mo), the translation not working. I tried install by zip (from repo), by compilation, by hand, nothing working. No restart help... :( 

Can you take a look at it if is my mistake or something different?
Thnx a lot.

**Comment by zagortenay333** [comment]
Yeah, It was a bug on my part. Should be fixed now.

**Comment by lev741** [comment]
Well, 
only partial success. It works somewhere, somewhere not. Watch the attached video.

(Color glitches produced by my virtual. Don`t worry..) 

[Záznam obrazovky z 2023-06-08 15-08-10.webm](https://github.com/zagortenay333/cronomix/assets/72345076/b4b88769-b15f-4671-8c34-01320e42f1be)

**Comment by zagortenay333** [comment]
You're right, it's broken.

I'm currently waiting for someone to answer my question here: https://discourse.gnome.org/t/can-inittranslations-be-called-outside-the-init-function/15661

Btw, can you checkout if the popups are still being cut off? I pushed a fix for those. You commented on the issue here: https://github.com/zagortenay333/cronomix/issues/223

**Comment by zagortenay333** [comment]
Ok, this should be fixed now for real.

**Comment by lev741** [comment]
Sorry,
nothing changes for translation. It looks the same.

[Záznam obrazovky z 2023-06-09 12-35-11.webm](https://github.com/zagortenay333/cronomix/assets/72345076/34bfb1f9-2d3d-43e9-9fe2-87b9effc06ef)

**Comment by zagortenay333** [comment]
Are you sure you got the latest download? What does the extension.js file look like?

**Comment by lev741** [comment]
Just now I tried with fresh source. Extension works in the same way. The basic screen of pomodoro works. Few textx too.

**Comment by zagortenay333** [comment]
What does your extension.js file look like?

**Comment by lev741** [comment]
Here is my in  ~/.local/share/gnome-shell/extensions/cronomix@zagortenay333
[extension.zip](https://github.com/zagortenay333/cronomix/files/11723251/extension.zip)

**Comment by zagortenay333** [comment]
That's not what the latest file looks like. I don't know how you go that. Download the zip from the README file. This one: https://github.com/zagortenay333/cronomix/blob/master/data/cronomix%40zagortenay333.zip

**Comment by lev741** [comment]
At first. Translations is working for now. Great. Thank you!
For me it is a little bit confusing, because sources from your github are the same except the comments on beginning of gnome.d.ts but the compiled result is completely different.

**Comment by zagortenay333** [comment]
To get the same zip as the one on github you have to use the ``pack`` script, not ``build``. The pack script ensures that the final js files retain blank lines.
