### ISSUE TITLE
alarm cannot edit

### ISSUE THREAD

**Issue by po818** [zagortenay333/timepp#230]
ubuntu 22.04 lts
gnome 42.5

when the alarm has a message,it can be edited or delete,but when there is no message,it cannot be edited or delete.when the mouse moves to the button,the edited button disappears.
![微信图片_20230608102930](https://github.com/zagortenay333/cronomix/assets/45204293/7a3463f3-6146-4ed4-a5bb-df9b5c5d3a0a)
![微信图片_20230608102923](https://github.com/zagortenay333/cronomix/assets/45204293/d8ebd801-302d-49f1-835f-b47f136cfa80)

**Comment by po818** [comment]
i have another question, how to clear the data of extension? i have tried uninstalling and installing again,but the alarm data is still there.

**Comment by zagortenay333** [comment]
This is an old and unsupported version of the extension. I won't fix any bugs on it.
