### ISSUE TITLE
Bug Report - Todo.txt Addon Freezing Issue

### ISSUE THREAD

**Issue by eliohz** [zagortenay333/timepp#232]
Hey Guys!

I wanted to reach out and inform you about a bug I encountered while using the Todo.txt addon. on
When attempting to delete a task, the addon freezes, causing the entire desktop to become unresponsive.

Steps to Reproduce:

Using latest Ubuntu 22.04 (GNOME/Wayland)
Open the Todo.txt addon from Top-Bar
Edit Task.
Try to delete a task.
The addon freezes, leading to a complete desktop freeze.

Thank you for your attention (:

Best regards,
Elio

**Comment by zagortenay333** [comment]
The latest version of this extension doesn't support todo.txt. Are you sure you installed the right version?

**Comment by eliohz** [comment]
Oh, I see. Sorry for the disturbance then!
Keep up your work. (:
Kind regards, and thanks for the fast feedback!

**Comment by zagortenay333** [comment]
No problem.
