### ISSUE TITLE
Clicking Dismiss in timer should stop the notification sound

### ISSUE THREAD

**Issue by Cylocation** [zagortenay333/timepp#233]
Current behavior:
There is no way to stop the alarm if the sound file chosen for the timer lasts for a few seconds or more. The dismiss button removes the visual notification but the sound will continue playing.

Expected behavior:
Clicking the Dismiss button should also cause the sound to stop playing.
This way if I choose a song, nature sounds, or other long sound file as my alarm notification it will turn off when I want it to.

**Comment by zagortenay333** [comment]
Fixed in the gnome 45 version.
