### ISSUE TITLE
Stopwatch paused when screen locked

### ISSUE THREAD

**Issue by k98kurz** [zagortenay333/timepp#235]
I had this running to time a genetic algorithm and stepped away from my computer for half an hour. When I returned, it was paused and read out just over 10 minutes. Is it not possible to continue timing something while the screen is locked? Is it not as simple as taking a timestamp when it starts and comparing to a new/current timestamp when updating the UI?

**Comment by zagortenay333** [comment]
Yeah, the extension gets disabled when you lock the screen. I tried adding support for it but there was weird behaviour in gnome-shell or a bug that made me give up on it.

**Comment by k98kurz** [comment]
That is unfortunate. If it is not really possible to fix, then I suppose I'll just close the issue.
