### ISSUE TITLE
Combine menu

### ISSUE THREAD

**Issue by android272** [zagortenay333/timepp#236]
This tool appears to be incredibly valuable. However, I have a suggestion to enhance its usability. It would be highly beneficial if there were options to toggle specific features on and off. Alternatively, consolidating these features under a single menu item with tabs could significantly optimize how much space is taken up in the gnome bar.

**Comment by zagortenay333** [comment]
You can disable individual applets as you wish. In the old version of the extension you used to be able to combine applets under a single menu, but I removed it for the sake of simplicity.
