### ISSUE TITLE
[Suggestion] Add option to change color

### ISSUE THREAD

**Issue by WilberRojas** [zagortenay333/timepp#237]
It would be great to have a funtion to change the color of background on fullscreen and fullscreen notifications:

![image](https://github.com/zagortenay333/cronomix/assets/74274632/b2f10900-26ad-44db-b1bb-4687150fe554)
![image](https://github.com/zagortenay333/cronomix/assets/74274632/da7918df-4bdb-483a-bf95-be5f4c23dbc4)

**Comment by zagortenay333** [comment]
These fullscreen notifs no longer exist, you're using  an  old  version of the extension. In the new version you can set the font size to big.
