### ISSUE TITLE
Pomodoro preset can't be anything but 4 iterations

### ISSUE THREAD

**Issue by taw00** [zagortenay333/timepp#241]
_Cronomix v44? Hard to tell what version is installed, actually. I presume whatever is current as of the the date of this ticket. How does one view what version of an extension is installed? Anyway …_

I create a new preset. I pick a label for it and set it to my new values: example, 35 minutes, 5, and 15. And "Long break every n pomodoros" to 3 (a nice cool 2.5 hours of pomodoroing).

But you go to use it , everything is correct, but the number of iterations is reset to 4.  If you set it to anything not 4, it will be reset to 4.

This makes me a sad pomodoroan. Please fix.  Thank you. :)

**Comment by zagortenay333** [comment]
Fixed in the gnome 45 version.
