### ISSUE TITLE
Alarm entry can't be edited

### ISSUE THREAD

**Issue by clov33** [zagortenay333/timepp#244]
![image](https://github.com/zagortenay333/cronomix/assets/112953997/e2272cb7-e48c-4888-8a22-3235ee0d64a3)
shows that it can be selected, but when i mouseover to the pencil icon, i can't select it, hence unable to modify/delete the entry.

also, may i know where is the data stored locally?

Thanks

**Comment by zagortenay333** [comment]
You seem to be using an outdated version of this extension.
