### ISSUE TITLE
[FEATURE REQUEST] add support for dash to panel

### ISSUE THREAD

**Issue by JE-Amouel** [zagortenay333/timepp#250]
hi, i recently switch to dash to panel to have more customization option and minimalistic look, but it look like cronomix buttons dont want to jump on dash to panel, is there any possibility for that?.
thank you.

I use GNOME 45, on ubuntu 23.10.

**Comment by zagortenay333** [comment]
What do you mean by jump?

**Comment by JE-Amouel** [comment]
when i am using gnome-shell original panel, the applet of cronomix shows well in gnome panel, but it not show up when on  panel of dash to panel.

**Comment by JE-Amouel** [comment]
i solve the problem it was a misunderstood with the way dash to panel organize the is panel,
thank you.
