### ISSUE TITLE
Navigating in/out of cronomix causes the menu to disapear.

### ISSUE THREAD

**Issue by MKrabs** [zagortenay333/timepp#261]
[Screencast from 17.05.2024 14:03:44.webm](https://github.com/zagortenay333/cronomix/assets/71791731/217b5ec8-6bfe-4798-9af8-2403d72f1816)

The small menu seen in the video also happens to open in the background of each menu. It does not seem to be clickable.

Ubuntu 22.04.4 LTS  
Gnome 42.9  
version 165

**Comment by zagortenay333** [comment]
You are using an old and unsupported version.
