### ISSUE TITLE
[BUG] Pop up window freezes when clicked edit on a task, everything became unclickable after then.

### ISSUE THREAD

**Issue by DarkIce000** [zagortenay333/timepp#264]
![freeze1 ](https://github.com/zagortenay333/cronomix/assets/116939251/711300d4-fc0c-4b8c-89c5-9d0d8c382296)
![freeze2](https://github.com/zagortenay333/cronomix/assets/116939251/bc1a2a5e-4060-41c3-a5bb-583423298153)
![2024-05-31_22-35](https://github.com/zagortenay333/cronomix/assets/116939251/0b86f87d-771f-48e5-aed8-519278e5cbb3)

Pop window appear for the task edit, got freezes and then after everything become unclickable nor delete, archive, cancel  button works. Only unfreeze this by locking the using windows+escape that take me to the lock screen. If you need more information, I will be helping you, I got that extension i am looking for months but some bugs are ruining the experience.

**Comment by zagortenay333** [comment]
You are using an old unmaintained version of the extension.
