### ISSUE TITLE
add dbus entry to toggle  cronomix 

### ISSUE THREAD

**Issue by JE-Amouel** [zagortenay333/timepp#265]
Hi,
cronomix has become a great combination when it comes to taking quick notes or making cheat sheets,

**The reason of this feature request**
however it's a bit embarrassing when you're in a terminal, having to constantly let go of your keyboard to click on the  menu's button , I'm getting used to it but I would really like you to include some functionality to make this beautiful extension even more more important for workflows.

**Some suggestion**
Here are some suggestions, which I hope will not leave you indifferent:

in general:
- it would be nice to add a pin button in the note preview interface, which will prevent the note preview from closing when you try to do something else in another part of the screen

for terminal users
- dbus options for:
open notes overview
hide notes oreview
pin notes overview
unpin notes overview

THANK YOU :pray: .

**Comment by zagortenay333** [comment]
I won't add this.

**Comment by JE-Amouel** [comment]
Is there any way to trigger cronomix display?
With keybinding or such...

**Comment by zagortenay333** [comment]
There is support for a variety of custom kebindings in the settings.

**Comment by JE-Amouel** [comment]
My main objectif was to be able to interact with cronomix within my terminal,
Thank you
